### PR TITLE
Some refactors

### PR DESCRIPTION
**Pull request by jennydaman**
- add `.editorconfig` and `.gitignore`
- take `import` out of `try/except`
- export function to get the local IP address (replacing the incomprehensible one-liner)
- bump version to 1.4.0

### CODE REVIEW

**Review by rudolphpienaar — COMMENTED** [review]
No, this is correct. At least it used to be. `cStringIO` was a custom module that I wrote a long time ago. This import can probably be completely removed since `cStringIO` should be all part of `pfmisc` now.

**Review by rudolphpienaar — COMMENTED** [review]
This rather cumbersome set of try/except was purposeful. Once upon a time.

It arose when developing/debugging on a system that might already have had these modules installed. In such a case, the idea is/was to attempt to first `import` the currently-being-edited source. If that failed, to then import the installed versions.

Does that make sense?

**Review by rudolphpienaar — APPROVED** [review]
Looks create!

**Review by rudolphpienaar — APPROVED** [review]
Yup.

**Review by rudolphpienaar — APPROVED** [review]
Good.

**Review by rudolphpienaar — CHANGES_REQUESTED** [review]
Like I touched on in the other comment -- please make sure this covers both local dev and installed deployed cases. In dev mode, you always want to make sure to import the correct and possibly changed modules.

**Review by rudolphpienaar — APPROVED** [review]
+1

**Comment by jennydaman** [comment]
> This rather cumbersome set of try/except was purposeful. Once upon a time.

Of course it's more convenient to provide a "best-effort" approach where the code does everything it can to recover from an invalid state, but that's a bad practice. We should fail execution as soon as we find out something is wrong with the client's `$PYTHONPATH`. Otherwise we'll just run into problems later on which would be even harder to trace...

When developing for pfmisc, it's up to the developer to make sure that pfmisc isn't installed in their virtual environment. It's better for the developer to look after themselves instead of trying to guess what the code is doing. It is easier to figure out a static runtime time error than it is to trace a logical error.

When using pfmisc as an imported library, client shouldn't be allowed to "hijack" the implementation of pfmisc. If they wanted to, then they should fork everything and export it under a different name.

**Comment by rudolphpienaar** [comment]
> > This rather cumbersome set of try/except was purposeful. Once upon a time.
> 
> Of course it's more convenient to provide a "best-effort" approach where the code does everything it can to recover from an invalid state, but that's a bad practice. We should fail execution as soon as we find out something is wrong with the client's `$PYTHONPATH`. Otherwise we'll just run into problems later on which would be even harder to trace...
> 
> When developing for pfmisc, it's up to the developer to make sure that pfmisc isn't installed in their virtual environment. It's better for the developer to look after themselves instead of trying to guess what the code is doing. It is easier to figure out a static runtime time error than it is to trace a logical error.
> 
> When using pfmisc as an imported library, client shouldn't be allowed to "hijack" the implementation of pfmisc. If they wanted to, then they should fork everything and export it under a different name.

Hmmmm... I see your point. This design pattern (anti-pattern? :-) ) is actually replicated in most of the ChRIS subsystems/code. 

And the issue isn't if something is wrong with the client's PYTHONPATH.. it was  trying to make sure that we always attempt to import a dev version even if a site-package instance exists. 

Do you have an elegant solution that works in both cases?

**Comment by jennydaman** [comment]
It's very much so an anti-pattern...

The elegant solution is virtual environments, of course.
But you're describing a different situation. Why would anyone want to import a dev version if the version exists in site-packages?

Examples:

- say you're working on `pfmisc`. You should be in a venv which doesn't have `pfmisc`.
- say you're working on `pfurl`. You should be using `pfmisc` from `site-package` of your venv.
- say you're working on `pfurl` and you want to use a custom "dev" version of `pfmisc`. You shouldn't be doing this, ever.

**Comment by jennydaman** [comment]
About `cStringIO`, not sure what that is about. According to a quick Google search, `cStringIO` is a python2 thing.

```python
try:
	from    cStringIO       import  StringIO
except ImportError:
	from 	io 		import 	StringIO
```

In Python 3, the above always reduces to

```python
from io import StringIO
```

**Pull request merged**
